#!/usr/bin/env python3
"""Generate src/device_map.rs from openrazer driver sources.

Usage:
  extract_openrazer_map.py <openrazer_root> <output_rs>
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PID_RE = re.compile(r"^#define\s+(USB_DEVICE_ID_RAZER_[A-Z0-9_]+)\s+0x([0-9A-Fa-f]+)\s*$")
CASE_RE = re.compile(r"^\s*case\s+(USB_DEVICE_ID_RAZER_[A-Z0-9_]+):")
TX_RE = re.compile(r"request\.transaction_id\.id\s*=\s*0x([0-9A-Fa-f]+)")
# Devices that always report "not charging" (AA-battery mice). OpenRazer has
# returned this via both sprintf() and, since commit 5315b632, sysfs_emit().
NO_CHARGE_RE = re.compile(r'return\s+(?:sprintf|sysfs_emit)\(buf,\s*"0\\n"\)')


def parse_pid_constants(header_text: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for line in header_text.splitlines():
        m = PID_RE.match(line)
        if m:
            out[m.group(1)] = int(m.group(2), 16)
    return out


def section(text: str, start_marker: str, end_marker: str) -> str:
    start = text.find(start_marker)
    if start < 0:
        raise RuntimeError(f"marker not found: {start_marker}")
    end = text.find(end_marker, start)
    if end < 0:
        raise RuntimeError(f"end marker not found: {end_marker}")
    return text[start:end]


def parse_tx_map(body: str) -> dict[str, int]:
    mapping: dict[str, int] = {}
    cases: list[str] = []

    for line in body.splitlines():
        c = CASE_RE.match(line)
        if c:
            cases.append(c.group(1))
            continue

        t = TX_RE.search(line)
        if t:
            tx = int(t.group(1), 16)
            for sym in cases:
                mapping[sym] = tx
            cases = []
            continue

        if "not supported" in line:
            cases = []

    return mapping


def parse_no_charge_symbols(charge_status_body: str) -> set[str]:
    no_charge: set[str] = set()
    cases: list[str] = []

    for line in charge_status_body.splitlines():
        c = CASE_RE.match(line)
        if c:
            cases.append(c.group(1))
            continue

        if NO_CHARGE_RE.search(line):
            no_charge.update(cases)
            cases = []
            continue

        t = TX_RE.search(line)
        if t:
            cases = []
            continue

        if "not supported" in line:
            cases = []

    return no_charge


def human_name(symbol: str) -> str:
    prefix = "USB_DEVICE_ID_RAZER_"
    base = symbol[len(prefix) :] if symbol.startswith(prefix) else symbol
    return "Razer " + " ".join(part.capitalize() for part in base.split("_"))


def emit(device_rows: list[tuple[int, int, bool, str, str]]) -> str:
    lines: list[str] = []
    lines.append("// This file is generated by tools/extract_openrazer_map.py")
    lines.append("// Source: openrazer/driver/razermouse_driver.c + razermouse_driver.h")
    lines.append("")
    lines.append("#[derive(Clone, Copy, Debug, Eq, PartialEq)]")
    lines.append("pub struct DeviceSupport {")
    lines.append("    pub pid: u16,")
    lines.append("    pub transaction_id: u8,")
    lines.append("    pub supports_charging_status: bool,")
    lines.append("    pub symbol: &'static str,")
    lines.append("    pub name: &'static str,")
    lines.append("}")
    lines.append("")
    lines.append("pub const KNOWN_DEVICE_SUPPORT: &[DeviceSupport] = &[")

    for pid, tx, supports, symbol, name in device_rows:
        lines.append(
            "    DeviceSupport { pid: 0x%04X, transaction_id: 0x%02X, supports_charging_status: %s, symbol: \"%s\", name: \"%s\" },"
            % (pid, tx, "true" if supports else "false", symbol, name)
        )

    lines.append("];")
    lines.append("")
    lines.append("pub fn known_device_support(pid: u16) -> Option<&'static DeviceSupport> {")
    lines.append("    KNOWN_DEVICE_SUPPORT")
    lines.append("        .binary_search_by_key(&pid, |entry| entry.pid)")
    lines.append("        .ok()")
    lines.append("        .map(|idx| &KNOWN_DEVICE_SUPPORT[idx])")
    lines.append("}")
    lines.append("")
    lines.append("#[cfg(test)]")
    lines.append("mod tests {")
    lines.append("    use super::known_device_support;")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn unknown_pid_returns_none() {")
    lines.append("        assert_eq!(known_device_support(0xFFFF), None);")
    lines.append("    }")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn charging_support_flag_is_populated_both_ways() {")
    lines.append("        // Guards against an upstream sysfs return-style change (e.g.")
    lines.append("        // sprintf -> sysfs_emit) silently zeroing out no-charge detection")
    lines.append("        // and marking every AA-battery mouse as charging-capable.")
    lines.append("        let map = super::KNOWN_DEVICE_SUPPORT;")
    lines.append("        assert!(map.iter().any(|d| d.supports_charging_status));")
    lines.append("        assert!(map.iter().any(|d| !d.supports_charging_status));")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: extract_openrazer_map.py <openrazer_root> <output_rs>", file=sys.stderr)
        return 2

    openrazer_root = Path(sys.argv[1]).expanduser().resolve()
    output_rs = Path(sys.argv[2]).expanduser().resolve()

    driver_h = openrazer_root / "driver" / "razermouse_driver.h"
    driver_c = openrazer_root / "driver" / "razermouse_driver.c"

    header_text = driver_h.read_text(encoding="utf-8")
    source_text = driver_c.read_text(encoding="utf-8")

    pid_by_symbol = parse_pid_constants(header_text)

    charge_level_body = section(
        source_text,
        "static ssize_t razer_attr_read_charge_level",
        "static ssize_t razer_attr_read_charge_status",
    )
    charge_status_body = section(
        source_text,
        "static ssize_t razer_attr_read_charge_status",
        "static ssize_t razer_attr_write_charge_effect",
    )

    tx_by_symbol = parse_tx_map(charge_level_body)
    no_charge_symbols = parse_no_charge_symbols(charge_status_body)

    # Guard: razer_attr_read_charge_status always lists AA-battery mice that
    # report "not charging". Finding none means the source-of-truth changed its
    # return style and NO_CHARGE_RE no longer matches, which would silently mark
    # every device as charging-capable. Fail loudly instead of emitting bad data.
    if not no_charge_symbols:
        raise RuntimeError(
            'no no-charge devices detected in razer_attr_read_charge_status; '
            'the OpenRazer sysfs return style likely changed (e.g. sprintf -> '
            'sysfs_emit). Update NO_CHARGE_RE in this script.'
        )

    rows: list[tuple[int, int, bool, str, str]] = []
    for symbol, tx in tx_by_symbol.items():
        pid = pid_by_symbol.get(symbol)
        if pid is None:
            continue
        supports_charging = symbol not in no_charge_symbols
        rows.append((pid, tx, supports_charging, symbol, human_name(symbol)))

    rows.sort(key=lambda row: (row[0], row[3]))

    output_rs.parent.mkdir(parents=True, exist_ok=True)
    output_rs.write_text(emit(rows), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
